#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
write_files:
  - path: /root/index.html
    content: |
      Todo Arrancado
runcmd:
  - docker run -d -v /root/index.html:/usr/share/nginx/html/index.html -p 80:80 nginx
