#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
runcmd:
  - fallocate -l 2G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  - cp /etc/fstab /etc/fstab.bak
  - echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab
  - echo 'vm.swappiness=10' >> /etc/sysctl.conf
  - echo 'vm.vfs_cache_pressure=50' >> /etc/sysctl.conf
